REQUIRED_NAMED_COLS = [
    {'label': 'trip_start_time_str', 'path': 'data.start_fmt_time'},
    {'label': 'trip_end_time_str', 'path': 'data.end_fmt_time'},
    {'label': 'start_coordinates', 'path': 'data.start_loc.coordinates'},
    {'label': 'end_coordinates', 'path': 'data.end_loc.coordinates'},
]

MULTILABEL_NAMED_COLS = [
    {'label': 'mode_confirm', 'path': 'data.user_input.mode_confirm'},
    {'label': 'purpose_confirm', 'path': 'data.user_input.purpose_confirm'},
    {'label': 'replaced_mode', 'path': 'data.user_input.replaced_mode'},
]

VALID_TRIP_COLS = [
    "data.start_local_dt",
    "data.start_fmt_time",
    "data.end_local_dt",
    "data.end_fmt_time",
    "data.duration",
    "data.distance",
    "data.start_loc.coordinates",
    "data.end_loc.coordinates",
    "user_id"
]

BINARY_TRIP_COLS = [
    'user_id',
    'data.start_place',
    'data.end_place',
]

valid_uuids_columns = [
    'user_token',
    'user_id',
    'update_ts',
    'total_trips',
    'labeled_trips',
    'first_trip',
    'last_trip',
    'last_call',
    'platform',
    'manufacturer',
    'app_version',
    'os_version',
    'phone_lang',
]

VALID_DEMOGRAPHICS_COLS = [
    'user_id',
    '_id',
    'data.ts',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.What_is_your_race_ethnicity',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.Are_you_a_student',
    'data.local_dt.year',
    'data.local_dt.month',
    'data.local_dt.day',
    'data.local_dt.hour',
    'data.local_dt.minute',
    'data.local_dt.second',
    'data.local_dt.weekday',
    'data.local_dt.timezone',
    'read_ts',
    'metadata.time_zone',
    'metadata.plugin',
    'metadata.write_ts',
    'metadata.platform',
    'metadata.read_ts',
    'metadata.key',
    'metadata.type',
    'metadata.write_local_dt.year',
    'metadata.write_local_dt.month',
    'metadata.write_local_dt.day',
    'metadata.write_local_dt.hour', 
    'metadata.write_local_dt.minute',
    'metadata.write_local_dt.second',
    'metadata.write_local_dt.weekday',
    'metadata.write_local_dt.timezone',
    'metadata.write_fmt_time',
    'data.ts',
    'data.xmlResponse',
    'data.label',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.attr.id',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.attr.xmlns:jr',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.attr.xmlns:orx',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.At_your_primary_job_do_you_ha',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.Which_best_describes_your_prim',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.Do_you_work_full_time_or_part_',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.Do_you_have_the_option_of_work',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.Please_describe_your_primary_job',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.Do_you_have_more_than_one_job',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.What_days_of_the_week_do_you_t',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_yk8eb99.How_many_days_do_you_usually_w_001',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.end',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.start',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.Which_one_below_describe_you_b',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.What_is_your_race_ethnicity',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.Are_you_a_student',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.What_is_the_highest_grade_or_d',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.do_you_consider_yourself_to_be',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.What_is_your_gender',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.How_old_are_you',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.Are_you_a_paid_worker',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_hg4zz25.Do_you_have_a_driver_license',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.meta.instanceID',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.How_long_you_had_this_conditio',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Including_yourself_how_many_w_001',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Including_yourself_how_many_p',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Do_you_own_or_rent_your_home',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Please_identify_which_category',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.If_you_were_unable_to_use_your',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Including_yourself_how_many_p_001',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Including_yourself_how_many_w',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.What_is_your_home_type',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.How_many_motor_vehicles_are_ow',
    'data.jsonDocResponse.aSfdnWs9LE6q8YEF7u9n85.group_pa5ah98.Do_you_have_a_condition_or_han',
    'data.fmt_time',
    'data.name',
    'data.version',
    
]

BINARY_DEMOGRAPHICS_COLS = [
    'user_id',
    '_id',
]